# Generated by Django 5.2.1 on 2025-06-04 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLakeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='accessright',
            name='can_access_all_versions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessright',
            name='allowed_versions',
            field=models.ManyToManyField(blank=True, to='myapp.datalakeversion'),
        ),
        migrations.CreateModel(
            name='DetailedAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dataset_name', models.CharField(max_length=100)),
                ('access_type', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.datalakeversion')),
            ],
        ),
    ]
